name: Reproduction
on:
  push:
    branches:
      - main
jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: reproduction
        run: |
          python3 -m pip install -r requirements.txt

      - name: Create .env file
        working-directory: reproduction
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env

      - name: Create output directory
        working-directory: reproduction
        run: |
          mkdir workflow_output

      - name: Run reproduction script
        working-directory: reproduction
        run: |
          python3 -m reproduction reproduction_input workflow_output

      - name: Upload reproduction results as artifact
        uses: actions/upload-artifact@v4
        with:
            name: reproduction-results
            path: reproduction/workflow_output/